Hello, my name is Aaron Kann.  In this data analysis, I seek to determine the point in the season in which a player's year to date averages become a better predictor of future outputs than a players previous year averages.

I expect that, in the first couple of weeks into a Premier League Season, a player's previous averages are a stronger predictive metric because a player's to date averages are suggested to a much greater degree of variance.  However, I hypothesize that around matchweek 6, a player's to date averages become a stronger metric because the recency advantage outweighs the larger variance.  

In addition, I expect that for metrics with a lower total count (goals, assists, yellow cards, etc.), last years output may be a more relevant factor for longer than metrics with a greater total count (total passes, shots attempted, clearances etc), because the high variance is magnified in these cases. 

Let's see if the data supports my hypotheses!

In [1]:
import csv, os, sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Read the data from the csv file
if not 'Premier_League_Team_Stats.csv' in os.listdir():
    os.chdir('..')
import fbref_scrape as fbref
from constants import *

In [2]:
def add_name_to_df(df, file):
    name = file.split('Matchlogs')[0]
    # get rid of the last underscore, and change all other underscores to spaces
    name = name[:-1].replace('_', ' ')
    # add the name all rows in the dataframe
    df['Name'] = name
    return df

In [3]:
prev_yr_df = pd.read_csv('Premier_League_Player_Stats.csv')

data_folder = 'Premier_League_Player_Matchlogs'
data_files = os.listdir(data_folder)
dfs = []
dfs_names = []

for file in data_files:
    if file.endswith('.csv'):
        file_path = os.path.join(data_folder, file)
        # read the csv file and process the data
        df = pd.read_csv(file_path)
        df = add_name_to_df(df, file)
        dfs.append(df)
        dfs_names.append(file)

dfs[0].head()

,game_started,game_count,dayofweek,comp,round,venue,result,team,opponent,position,...,passes_completed,passes,passes_pct,progressive_passes,carries,progressive_carries,take_ons,take_ons_won,match_report,Name
0,Y,1,Mon,Premier League,Matchweek 1,Home,W 1-0,Manchester Utd,Wolves,RB,...,47,51,92.2,3,42,1,4,3,Match Report,Aaron Wan Bissaka
1,Y,2,Sat,Premier League,Matchweek 2,Away,L 0-2,Manchester Utd,Tottenham,RB,...,38,44,86.4,1,29,1,2,1,Match Report,Aaron Wan Bissaka
2,Y,3,Sat,Premier League,Matchweek 3,Home,W 3-2,Manchester Utd,Nott'ham Forest,RB,...,58,69,84.1,9,55,7,2,1,Match Report,Aaron Wan Bissaka
3,Y,4,Sun,Premier League,Matchweek 4,Away,L 1-3,Manchester Utd,Arsenal,RB,...,44,54,81.5,2,30,2,0,0,Match Report,Aaron Wan Bissaka
4,N,5,Sat,Premier League,Matchweek 5,Home,L 1-3,Manchester Utd,Brighton,CB,...,10,11,90.9,1,5,0,0,0,Match Report,Aaron Wan Bissaka

In [4]:
def update_avgs(season_avgs, row, index):
    #iterate through the stats in season_avgs and update the averages
    for stat in season_avgs.keys():
        if stat in row.keys():
            if stat == "team":
                continue
            season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
    return season_avgs

# Get a player name from the matchlogs file name
def get_player_name(filename):
    return filename.split("_Matchlogs")[0].replace('_', ' ')

def get_player_prev_yr_statline(prev_yr_df, player_name):
    return prev_yr_df[prev_yr_df['name'] == player_name]

In [5]:
stats_wanted = fbref.get_stats_wanted('fbref')
stats_wanted.remove('name')
stats_wanted.remove('team')
stats_wanted.append('game_count')
df_as_list = list()

for i in range(len(dfs)): #iterates through each player's data
    
    # create a new row, with the season totals as of matchweek 0 (ie all zero)
    season_avgs = pd.Series(data=[0]*len(stats_wanted), index=stats_wanted)
    # print(season_avgs, last_five_avgs)


    for index, row in dfs[i].iterrows(): #iterates through each game of each players data
        # get rid of the buggy goalie statlines, which have no stats TODO: fix this
        if "take_ons_won" not in row.keys():
            continue

        dfrow = pd.concat([row, season_avgs.add_suffix("_szn")], axis=0)
        season_avgs = update_avgs(season_avgs, row, index)

        
        #add last season averages to the list
        dfrow['player_name'] = get_player_name(dfs_names[i])
        prev_yr_statline = get_player_prev_yr_statline(prev_yr_df, dfrow['player_name'])
        
        #iterate through the stats in prev_yr_statline and add them to the row
        if prev_yr_statline.empty:
            continue
        else:
            for stat in prev_yr_statline.keys():
                if prev_yr_statline["games"].iloc[0] != 0 and type(prev_yr_statline[stat].iloc[0]) ==  np.int64:
                    # print(stat)
                    dfrow[stat + "_prev_yr"] = prev_yr_statline[stat].iloc[0] / prev_yr_statline['games'].iloc[0]
                else:
                    dfrow[stat + "_prev_yr"] = prev_yr_statline[stat].iloc[0]
            
        #add the row to the list        
        df_as_list.append(dfrow)

    #end game loop
#end player loop

df = pd.DataFrame(df_as_list)
df.head()

C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '77.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '89.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '46.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '64.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '73.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '10.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '26.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '16.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '45.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '70.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '8.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '55.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '45.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '75.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '87.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '62.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '77.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '55.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '52.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '14.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '74.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '46.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '63.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)
C:\Users\Aaron\AppData\Local\Temp\ipykernel_21788\3171090442.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  season_avgs[stat] = (season_avgs[stat]*index + row[stat])/(index+1)

,game_started,game_count,dayofweek,comp,round,venue,result,team,opponent,position,...,crosses_prev_yr,shots_prev_yr,shots_on_target_prev_yr,games,gk_saves,clearances,assisted_shots,fouled,crosses,fouls
0,Y,1,Mon,Premier League,Matchweek 1,Home,W 1-0,Manchester Utd,Wolves,RB,...,0.0,0.526316,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Y,2,Sat,Premier League,Matchweek 2,Away,L 0-2,Manchester Utd,Tottenham,RB,...,0.0,0.526316,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Y,3,Sat,Premier League,Matchweek 3,Home,W 3-2,Manchester Utd,Nott'ham Forest,RB,...,0.0,0.526316,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Y,4,Sun,Premier League,Matchweek 4,Away,L 1-3,Manchester Utd,Arsenal,RB,...,0.0,0.526316,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N,5,Sat,Premier League,Matchweek 5,Home,L 1-3,Manchester Utd,Brighton,CB,...,0.0,0.526316,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.to_csv('prev_yr_output.csv', index=False)

In [7]:
# Iterate though each of the matchweeks, performing a linear regression on the data
for i in range(38):
    if i in [0, 1]:
        continue
    # Get the data for the current matchweek
    matchweek_data = df[df['game_count'] == i]
    # Perform a linear regression on the data
    # Get the x and y values
    Y = np.array(matchweek_data['passes'])
    X = np.array(matchweek_data[['passes_prev_yr', 'passes_szn']])
    X = sm.add_constant(X)

    model = sm.OLS(Y, X).fit()
    
    
    if (i in [2, 4, 6, 11, 19, 28]):
        print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.392
Model:                            OLS   Adj. R-squared:                  0.387
Method:                 Least Squares   F-statistic:                     74.24
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           1.33e-25
Time:                        08:29:02   Log-Likelihood:                -1018.7
No. Observations:                 233   AIC:                             2043.
Df Residuals:                     230   BIC:                             2054.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         17.3394      2.057      8.430      0.000      13.287      21.392
x1             0.0038      0.003      1.285      0.200      -0.002       0.010
x2             0.5462      0.046     11.981      0.000       0.456       0.636
==============================================================================
Omnibus:                       18.918   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               23.485
Skew:                           0.595   Prob(JB):                     7.95e-06
Kurtosis:                       4.001   Cond. No.                         764.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.395
Model:                            OLS   Adj. R-squared:                  0.390
Method:                 Least Squares   F-statistic:                     75.01
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           8.34e-26
Time:                        08:29:02   Log-Likelihood:                -1050.4
No. Observations:                 233   AIC:                             2107.
Df Residuals:                     230   BIC:                             2117.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.4672      2.797      4.458      0.000       6.957      17.977
x1            -0.0050      0.003     -1.461      0.145      -0.012       0.002
x2             0.7866      0.064     12.236      0.000       0.660       0.913
==============================================================================
Omnibus:                       41.196   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               90.203
Skew:                           0.843   Prob(JB):                     2.59e-20
Kurtosis:                       5.539   Cond. No.                         907.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.364
Model:                            OLS   Adj. R-squared:                  0.359
Method:                 Least Squares   F-statistic:                     65.85
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           2.44e-23
Time:                        08:29:02   Log-Likelihood:                -1026.0
No. Observations:                 233   AIC:                             2058.
Df Residuals:                     230   BIC:                             2068.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         11.1698      2.664      4.192      0.000       5.920      16.419
x1             0.0055      0.003      1.789      0.075      -0.001       0.012
x2             0.6800      0.061     11.173      0.000       0.560       0.800
==============================================================================
Omnibus:                       18.666   Durbin-Watson:                   1.925
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               20.695
Skew:                           0.693   Prob(JB):                     3.21e-05
Kurtosis:                       3.458   Cond. No.                         960.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.342
Method:                 Least Squares   F-statistic:                     61.25
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           4.74e-22
Time:                        08:29:02   Log-Likelihood:                -1030.7
No. Observations:                 233   AIC:                             2067.
Df Residuals:                     230   BIC:                             2078.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         10.8252      2.968      3.647      0.000       4.977      16.674
x1             0.0079      0.003      2.535      0.012       0.002       0.014
x2             0.7264      0.069     10.510      0.000       0.590       0.863
==============================================================================
Omnibus:                       11.909   Durbin-Watson:                   2.232
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               14.083
Skew:                           0.423   Prob(JB):                     0.000875
Kurtosis:                       3.857   Cond. No.                     1.05e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.485
Model:                            OLS   Adj. R-squared:                  0.480
Method:                 Least Squares   F-statistic:                     100.1
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           2.19e-31
Time:                        08:29:02   Log-Likelihood:                -926.51
No. Observations:                 216   AIC:                             1859.
Df Residuals:                     213   BIC:                             1869.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.5247      2.793      1.262      0.208      -1.980       9.029
x1            -0.0020      0.003     -0.688      0.492      -0.008       0.004
x2             0.9185      0.065     14.151      0.000       0.791       1.046
==============================================================================
Omnibus:                        4.660   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                4.497
Skew:                           0.257   Prob(JB):                        0.106
Kurtosis:                       3.486   Cond. No.                     1.06e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.06e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.476
Model:                            OLS   Adj. R-squared:                  0.470
Method:                 Least Squares   F-statistic:                     70.05
Date:                Wed, 21 Jan 2026   Prob (F-statistic):           2.32e-22
Time:                        08:29:02   Log-Likelihood:                -671.33
No. Observations:                 157   AIC:                             1349.
Df Residuals:                     154   BIC:                             1358.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.4956      3.193      1.095      0.275      -2.812       9.804
x1             0.0019      0.003      0.566      0.572      -0.005       0.008
x2             0.8489      0.072     11.787      0.000       0.707       0.991
==============================================================================
Omnibus:                        6.648   Durbin-Watson:                   2.083
Prob(Omnibus):                  0.036   Jarque-Bera (JB):                9.710
Skew:                          -0.182   Prob(JB):                      0.00779
Kurtosis:                       4.163   Cond. No.                     1.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.