We'll use this script to compare lines from the two sites.

A reminder that for a double to be a greater value on PrizePicks than DraftKings, 
the two bets must multiply to a value lesser than three.

In [13]:
# from draft_kings import get_dk_data# this will run the script that scrapes the data into the json file we will use
import sys
sys.path.append('..')  # Add the parent directory to the sys.path
from constants import *
from pp_scrape import get_data

In [14]:
import json, csv, math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
COLLEGE_BASKETBALL = "20"
MLB = "2"
NBA = "7"

# get_dk_data("nba") # this will run the script that scrapes the data into the json file we will use
get_data(MLB) # this will run the script that scrapes the data into the json file we will use

dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 1.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 0, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hits+Runs+RBIs', 'stat_type': 'Hits+Runs+RBIs', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:58-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 5.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 5, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hitter Fantasy Score', 'stat_type': 'Hitter Fantasy Score', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:59-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 1.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 0, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hits+Runs+RBIs', 'stat_type': 'Hits+Runs+RBIs', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:59-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 5.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 2, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hitter Fantasy Score', 'stat_type': 'Hitter Fantasy Score', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:59-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 0.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 503, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Walks', 'stat_type': 'Walks', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:04:04-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-12T06:10:00-04:00', 'custom_image': None, 'description': 'CHC', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 8.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 1, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hitter Fantasy Score', 'stat_type': 'Hitter Fantasy Score', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:34-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-12T06:10:00-04:00', 'custom_image': None, 'description': 'CHC', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 1.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 503, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Total Bases', 'stat_type': 'Total Bases', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:41-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-12T06:10:00-04:00', 'custom_image': None, 'description': 'CHC', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 6.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 3, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hitter Fantasy Score', 'stat_type': 'Hitter Fantasy Score', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:34-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 5.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 4, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Hitter Fantasy Score', 'stat_type': 'Hitter Fantasy Score', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:59-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-12T06:10:00-04:00', 'custom_image': None, 'description': 'CHC', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 4, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 500, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Pitcher Strikeouts', 'stat_type': 'Pitcher Strikeouts', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:40-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-12T06:10:00-04:00', 'custom_image': None, 'description': 'CHC', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 1.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 501, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Earned Runs Allowed', 'stat_type': 'Earned Runs Allowed', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:40-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 4, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 502, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Pitcher Strikeouts', 'stat_type': 'Pitcher Strikeouts', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:04:04-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 13.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 502, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Pitching Outs', 'stat_type': 'Pitching Outs', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:04:04-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-12T06:10:00-04:00', 'custom_image': None, 'description': 'CHC', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 0.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 503, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Runs', 'stat_type': 'Runs', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:03:41-04:00'}
dict_keys(['adjusted_odds', 'board_time', 'custom_image', 'description', 'end_time', 'flash_sale_line_score', 'game_id', 'hr_20', 'in_game', 'is_live', 'is_promo', 'line_score', 'odds_type', 'projection_type', 'rank', 'refundable', 'start_time', 'stat_display_name', 'stat_type', 'status', 'tv_channel', 'updated_at'])
{'adjusted_odds': None, 'board_time': '2025-03-16T06:10:00-04:00', 'custom_image': None, 'description': 'LAD', 'end_time': None, 'flash_sale_line_score': None, 'game_id': 'MLB_game_vgI7OChHVkIfNYLfI5QMNB0r', 'hr_20': True, 'in_game': False, 'is_live': False, 'is_promo': False, 'line_score': 0.5, 'odds_type': 'standard', 'projection_type': 'Single Stat', 'rank': 505, 'refundable': True, 'start_time': '2025-03-19T06:10:00-04:00', 'stat_display_name': 'Total Bases', 'stat_type': 'Total Bases', 'status': 'pre_game', 'tv_channel': None, 'updated_at': '2025-03-18T21:04:04-04:00'}

[{'name': 'Seiya Suzuki',
  'opponent': 'LAD',
  'Hits+Runs+RBIs': 1.5,
  'Hitter Fantasy Score': 5.5},
 {'name': 'Kyle Tucker',
  'opponent': 'LAD',
  'Hits+Runs+RBIs': 1.5,
  'Hitter Fantasy Score': 5.5,
  'Walks': 0.5},
 {'name': 'Shohei Ohtani',
  'opponent': 'CHC',
  'Hitter Fantasy Score': 8.5,
  'Total Bases': 1.5},
 {'name': 'Teoscar Hernandez', 'opponent': 'CHC', 'Hitter Fantasy Score': 6.5},
 {'name': 'Ian Happ', 'opponent': 'LAD', 'Hitter Fantasy Score': 5.5},
 {'name': 'Roki Sasaki',
  'opponent': 'CHC',
  'Pitcher Strikeouts': 4,
  'Earned Runs Allowed': 1.5},
 {'name': 'Justin Steele',
  'opponent': 'LAD',
  'Pitcher Strikeouts': 4,
  'Pitching Outs': 13.5},
 {'name': 'Tommy Edman', 'opponent': 'CHC', 'Runs': 0.5},
 {'name': 'Pete Crow-Armstrong', 'opponent': 'LAD', 'Total Bases': 0.5}]

In [16]:
more_mlb_props = ['Correct Score', 'Most Regular Season Strikeouts',
       'Most Regular Season Hits', 'Most Regular Season Runs', 'Award Winner',
       'Most Regular Season Saves', 'Most Regular Season Home Runs',
       'Pitcher Most Regular Season Wins', 'Most Regular Season Stolen Bases',
       'To Make the Playoffs', 'Division Winner', 'League Winner', 'Winner',
       'Race To 10 Regular Season Wins',
       'Freddie Freeman - 1st Plate Appearance - Exact Result',
       'Shohei Ohtani - 1st Plate Appearance - Exact Result',
       'Seiya Suzuki - 1st Plate Appearance - Exact Result',
       'Kyle Tucker - 1st Plate Appearance - Exact Result',
       'Ian Happ - 1st Plate Appearance - Exact Result',
       'Tommy Edman - 1st Plate Appearance - Exact Result',
       'Run Line - 1st 5 Innings',
       'Both Teams to Score X+ Runs - 1st 5 Innings',
       'Total Runs - 1st 5 Innings', 'Runs - 6th Inning',
       'Runs - 5th Inning', 'Runs - 1st Inning', 'Runs - 4th Inning',
       'Runs - 9th Inning', 'Runs - 7th Inning', 'Runs - 8th Inning',
       'Runs - 3rd Inning', 'Runs - 2nd Inning', 'Race to 3 Runs',
       'Race to 5 Runs', 'Race to 6 Runs', 'Race to 7 Runs', 'Race to 4 Runs']

In [17]:
PROP_LABEL_STRING = "prop_label"
PARTICIPANT_LABEL_STRING = "participant"


dk_lines = pd.read_csv('draftkings_mlb.csv', encoding='latin-1')
# print(dk_lines['category'].value_counts())
# # list the items that appear multiple times
# print(dk_lines[PROP_LABEL_STRING].value_counts()[dk_lines[PROP_LABEL_STRING].value_counts() > 2].keys())
game_props = ["Game Lines", "Team Props", "Halves", "Game Props", "Total", "Innings", "Total Runs - 1st 5 Innings", "Quick Hits", "Game Leaders", "Game Lines", "Total", "Most Points", "Moneyline", "Halves", "Total 1st Half", "Moneyline 1st Half", "Quarters", "Total 1st Quarter", "Moneyline 1st Quarter", "Q1 Player Props"]
# game_props = game_props + more_mlb_props



player_lines = dk_lines[~dk_lines[PROP_LABEL_STRING].isin(game_props)]
player_lines = player_lines[~player_lines[PARTICIPANT_LABEL_STRING].isin(game_props)]
print(player_lines[PROP_LABEL_STRING].value_counts())


player_lines

prop_label
Correct Score                        92
Most Regular Season Strikeouts       86
Most Regular Season Hits             84
Most Regular Season Runs             80
Award Winner                         76
                                     ..
BAL Orioles Regular Season Wins       2
BOS Red Sox Regular Season Wins       2
CHI White Sox Regular Season Wins     2
CIN Reds Regular Season Wins          2
Run Line                              2
Name: count, Length: 93, dtype: int64

,providerOutcomeId,providerId,providerOfferId,label,oddsAmerican,oddsDecimal,oddsDecimalDisplay,oddsFractional,line,participant,participantType,main,sortOrder,tags,participants,category,prop_label
0,0HC78801697N150_3,2,2_78801697,LA Dodgers,114,2.140000,2.14,57/50,-1.5,LA Dodgers,Team,True,-1501,"['MainPointLine', 'SGP']","[{'id': '29931', 'name': 'LA Dodgers', 'type':...",Game Lines,Run Line
1,0HC78801697P150_1,2,2_78801697,CHI Cubs,-135,1.740741,1.74,20/27,1.5,CHI Cubs,Team,True,-1499,"['MainPointLine', 'SGP']","[{'id': '29894', 'name': 'CHI Cubs', 'type': '...",Game Lines,Run Line
6,0QA239088993#187857891_13L84240Q1-446308922Q20,2,239088993,1+,550,6.500000,6.50,11/2,None Specified,Andy Pages,Unknown,True,65091,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '459808', 'name': 'Andy Pages', 'type'...",Batter Props,Andy Pages Home Runs
7,0QA239088993#187857892_13L84240Q1475630076Q20,2,239088993,2+,8000,81.000000,81.00,80/1,None Specified,Andy Pages,Unknown,None Specified,810092,['SGP'],"[{'id': '459808', 'name': 'Andy Pages', 'type'...",Batter Props,Andy Pages Home Runs
8,0QA239088999#187857917_13L84240Q1-446308922Q20,2,239088999,1+,900,10.000000,10.00,9/1,None Specified,Carson Kelly,Unknown,True,100017,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32117', 'name': 'Carson Kelly', 'type...",Batter Props,Carson Kelly Home Runs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1064,0QA225778502#111244066_13L84240Q11284100Q2-1,2,225778502,Willy Adames,13000,131.000000,131.00,130/1,None Specified,Willy Adames,Unknown,None Specified,1310066,None Specified,"[{'name': 'Willy Adames', 'type': 'Team'}]",Awards,Award Winner
1065,0QA225778502#111244076_13L84240Q11100850Q2-1,2,225778502,Oneil Cruz,13000,131.000000,131.00,130/1,None Specified,Oneil Cruz,Unknown,None Specified,1310076,None Specified,"[{'name': 'Oneil Cruz', 'type': 'Team'}]",Awards,Award Winner
1066,0QA225778502#170036355_13L84240Q12183046Q2-1,2,225778502,Pete Crow-Armstrong,15000,151.000000,151.00,150/1,None Specified,Pete Crow-Armstrong,Unknown,None Specified,1510055,None Specified,"[{'name': 'Pete Crow-Armstrong', 'type': 'Team'}]",Awards,Award Winner
1067,0QA225778502#111244083_13L84240Q1928008Q2-1,2,225778502,Luis Arraez,15000,151.000000,151.00,150/1,None Specified,Luis Arraez,Unknown,None Specified,1510083,None Specified,"[{'name': 'Luis Arraez', 'type': 'Team'}]",Awards,Award Winner
1068,0QA225778502#111244096_13L84240Q11854221Q2-1,2,225778502,CJ Abrams,15000,151.000000,151.00,150/1,None Specified,CJ Abrams,Unknown,None Specified,1510096,None Specified,"[{'name': 'CJ Abrams', 'type': 'Team'}]",Awards,Award Winner

In [24]:
print(player_lines['category'].value_counts())

player_lines = player_lines[player_lines['category'].isin(['Batter Props', 'Pitcher Props', 'Player Props'])]
player_lines

category
Batter Props     36
Pitcher Props    10
Name: count, dtype: int64

,providerOutcomeId,providerId,providerOfferId,label,oddsAmerican,oddsDecimal,oddsDecimalDisplay,oddsFractional,line,participant,participantType,main,sortOrder,tags,participants,category,prop_label
6,0QA239088993#187857891_13L84240Q1-446308922Q20,2,239088993,1+,550,6.500000,6.50,11/2,None Specified,Andy Pages,Unknown,True,65091,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '459808', 'name': 'Andy Pages', 'type'...",Batter Props,Andy Pages Home Runs
7,0QA239088993#187857892_13L84240Q1475630076Q20,2,239088993,2+,8000,81.000000,81.00,80/1,None Specified,Andy Pages,Unknown,None Specified,810092,['SGP'],"[{'id': '459808', 'name': 'Andy Pages', 'type'...",Batter Props,Andy Pages Home Runs
8,0QA239088999#187857917_13L84240Q1-446308922Q20,2,239088999,1+,900,10.000000,10.00,9/1,None Specified,Carson Kelly,Unknown,True,100017,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32117', 'name': 'Carson Kelly', 'type...",Batter Props,Carson Kelly Home Runs
9,0QA239088999#187857918_13L84240Q1475630076Q20,2,239088999,2+,10000,101.000000,101.00,100/1,None Specified,Carson Kelly,Unknown,None Specified,1010018,['SGP'],"[{'id': '32117', 'name': 'Carson Kelly', 'type...",Batter Props,Carson Kelly Home Runs
10,0QA239088978#187857874_13L84240Q1-446308922Q20,2,239088978,1+,650,7.500000,7.50,13/2,None Specified,Dansby Swanson,Unknown,True,75074,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32252', 'name': 'Dansby Swanson', 'ty...",Batter Props,Dansby Swanson Home Runs
11,0QA239088978#187857877_13L84240Q1475630076Q20,2,239088978,2+,7500,76.000000,76.00,75/1,None Specified,Dansby Swanson,Unknown,None Specified,760077,['SGP'],"[{'id': '32252', 'name': 'Dansby Swanson', 'ty...",Batter Props,Dansby Swanson Home Runs
12,0QA239088998#187857915_13L84240Q1-446308922Q20,2,239088998,1+,550,6.500000,6.50,11/2,None Specified,Freddie Freeman,Unknown,True,65015,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32190', 'name': 'Freddie Freeman', 't...",Batter Props,Freddie Freeman Home Runs
13,0QA239088998#187857916_13L84240Q1475630076Q20,2,239088998,2+,6000,61.000000,61.00,60/1,None Specified,Freddie Freeman,Unknown,None Specified,610016,['SGP'],"[{'id': '32190', 'name': 'Freddie Freeman', 't...",Batter Props,Freddie Freeman Home Runs
14,0QA239088994#187857906_13L84240Q1-446308922Q20,2,239088994,1+,550,6.500000,6.50,11/2,None Specified,Ian Happ,Unknown,True,65006,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32388', 'name': 'Ian Happ', 'type': '...",Batter Props,Ian Happ Home Runs
15,0QA239088994#187857907_13L84240Q1475630076Q20,2,239088994,2+,5500,56.000000,56.00,55/1,None Specified,Ian Happ,Unknown,None Specified,560007,['SGP'],"[{'id': '32388', 'name': 'Ian Happ', 'type': '...",Batter Props,Ian Happ Home Runs
16,0QA239088971#187857896_13L84240Q1-446308922Q20,2,239088971,1+,1800,19.000000,19.00,18/1,None Specified,Jon Berti,Unknown,True,190096,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '31467', 'name': 'Jon Berti', 'type': ...",Batter Props,Jon Berti Home Runs
17,0QA239088971#187857897_13L84240Q1475630076Q20,2,239088971,2+,20000,201.000000,201.00,200/1,None Specified,Jon Berti,Unknown,None Specified,2010097,['SGP'],"[{'id': '31467', 'name': 'Jon Berti', 'type': ...",Batter Props,Jon Berti Home Runs
18,0QA239088991#187857884_13L84240Q1-446308922Q20,2,239088991,1+,450,5.500000,5.50,9/2,None Specified,Kyle Tucker,Unknown,True,55084,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32010', 'name': 'Kyle Tucker', 'type'...",Batter Props,Kyle Tucker Home Runs
19,0QA239088991#187857885_13L84240Q1475630076Q20,2,239088991,2+,4500,46.000000,46.00,45/1,None Specified,Kyle Tucker,Unknown,None Specified,460085,['SGP'],"[{'id': '32010', 'name': 'Kyle Tucker', 'type'...",Batter Props,Kyle Tucker Home Runs
20,0QA239089010#187857933_13L84240Q1-446308922Q20,2,239089010,1+,850,9.500000,9.50,17/2,None Specified,Matt Shaw,Unknown,True,95033,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '721198', 'name': 'Matt Shaw', 'type':...",Batter Props,Matt Shaw Home Runs
21,0QA239089010#187857934_13L84240Q1475630076Q20,2,239089010,2+,10000,101.000000,101.00,100/1,None Specified,Matt Shaw,Unknown,None Specified,1010034,['SGP'],"[{'id': '721198', 'name': 'Matt Shaw', 'type':...",Batter Props,Matt Shaw Home Runs
22,0QA239088997#187857913_13L84240Q1-446308922Q20,2,239088997,1+,380,4.800000,4.80,19/5,None Specified,Max Muncy,Unknown,True,48013,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32690', 'name': 'Max Muncy', 'type': ...",Batter Props,Max Muncy Home Runs
23,0QA239088997#187857914_13L84240Q1475630076Q20,2,239088997,2+,3000,31.000000,31.00,30/1,None Specified,Max Muncy,Unknown,None Specified,310014,['SGP'],"[{'id': '32690', 'name': 'Max Muncy', 'type': ...",Batter Props,Max Muncy Home Runs
24,0QA239089009#187857935_13L84240Q1-446308922Q20,2,239089009,1+,550,6.500000,6.50,11/2,None Specified,Michael Busch,Unknown,True,65035,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '459806', 'name': 'Michael Busch', 'ty...",Batter Props,Michael Busch Home Runs
25,0QA239089009#187857936_13L84240Q1475630076Q20,2,239089009,2+,6500,66.000000,66.00,65/1,None Specified,Michael Busch,Unknown,None Specified,660036,['SGP'],"[{'id': '459806', 'name': 'Michael Busch', 'ty...",Batter Props,Michael Busch Home Runs
26,0QA239214028#188388413_13L84240Q1-446308922Q20,2,239214028,1+,600,7.000000,7.00,6/1,None Specified,Michael Conforto,Unknown,True,70013,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '31762', 'name': 'Michael Conforto', '...",Batter Props,Michael Conforto Home Runs
27,0QA239214028#188388414_13L84240Q1475630076Q20,2,239214028,2+,7000,71.000000,71.00,70/1,None Specified,Michael Conforto,Unknown,None Specified,710014,['SGP'],"[{'id': '31762', 'name': 'Michael Conforto', '...",Batter Props,Michael Conforto Home Runs
28,0QA239088987#187857838_13L84240Q1-446308922Q20,2,239088987,1+,1100,12.000000,12.00,11/1,None Specified,Miguel Rojas,Unknown,True,120038,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32765', 'name': 'Miguel Rojas', 'type...",Batter Props,Miguel Rojas Home Runs
29,0QA239088987#187857839_13L84240Q1475630076Q20,2,239088987,2+,14000,141.000000,141.00,140/1,None Specified,Miguel Rojas,Unknown,None Specified,1410039,['SGP'],"[{'id': '32765', 'name': 'Miguel Rojas', 'type...",Batter Props,Miguel Rojas Home Runs
30,0QA239089014#187857952_13L84240Q1-446308922Q20,2,239089014,1+,850,9.500000,9.50,17/2,None Specified,Pete Crow-Armstrong,Unknown,True,95052,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '494682', 'name': 'Pete Crow-Armstrong...",Batter Props,Pete Crow-Armstrong Home Runs
31,0QA239089014#187857953_13L84240Q1475630076Q20,2,239089014,2+,9000,91.000000,91.00,90/1,None Specified,Pete Crow-Armstrong,Unknown,None Specified,910053,['SGP'],"[{'id': '494682', 'name': 'Pete Crow-Armstrong...",Batter Props,Pete Crow-Armstrong Home Runs
32,0QA239088995#187857908_13L84240Q1-446308922Q20,2,239088995,1+,500,6.000000,6.00,5/1,None Specified,Seiya Suzuki,Unknown,True,60008,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '112834', 'name': 'Seiya Suzuki', 'typ...",Batter Props,Seiya Suzuki Home Runs
33,0QA239088995#187857909_13L84240Q1475630076Q20,2,239088995,2+,5500,56.000000,56.00,55/1,None Specified,Seiya Suzuki,Unknown,None Specified,560009,['SGP'],"[{'id': '112834', 'name': 'Seiya Suzuki', 'typ...",Batter Props,Seiya Suzuki Home Runs
34,0QA239088979#187857901_13L84240Q1-446308922Q20,2,239088979,1+,280,3.800000,3.80,14/5,None Specified,Shohei Ohtani,Unknown,True,38001,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32242', 'name': 'Shohei Ohtani', 'typ...",Batter Props,Shohei Ohtani Home Runs
35,0QA239088979#187857902_13L84240Q1475630076Q20,2,239088979,2+,2000,21.000000,21.00,20/1,None Specified,Shohei Ohtani,Unknown,None Specified,210002,['SGP'],"[{'id': '32242', 'name': 'Shohei Ohtani', 'typ...",Batter Props,Shohei Ohtani Home Runs
36,0QA239088970#187857868_13L84240Q1-446308922Q20,2,239088970,1+,380,4.800000,4.80,19/5,None Specified,Teoscar Hernandez,Unknown,True,48068,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '31969', 'name': 'Teoscar Hernandez', ...",Batter Props,Teoscar Hernandez Home Runs
37,0QA239088970#187857869_13L84240Q1475630076Q20,2,239088970,2+,3000,31.000000,31.00,30/1,None Specified,Teoscar Hernandez,Unknown,None Specified,310069,['SGP'],"[{'id': '31969', 'name': 'Teoscar Hernandez', ...",Batter Props,Teoscar Hernandez Home Runs
38,0QA239089022#187857978_13L84240Q1-446308922Q20,2,239089022,1+,600,7.000000,7.00,6/1,None Specified,Tommy Edman,Unknown,True,70078,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32461', 'name': 'Tommy Edman', 'type'...",Batter Props,Tommy Edman Home Runs
39,0QA239089022#187857979_13L84240Q1475630076Q20,2,239089022,2+,7500,76.000000,76.00,75/1,None Specified,Tommy Edman,Unknown,None Specified,760079,['SGP'],"[{'id': '32461', 'name': 'Tommy Edman', 'type'...",Batter Props,Tommy Edman Home Runs
40,0QA239088974#187857840_13L84240Q1-446308922Q20,2,239088974,1+,425,5.250000,5.25,17/4,None Specified,Will Smith (LAD),Unknown,True,52540,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '32725', 'name': 'Will Smith (LAD)', '...",Batter Props,Will Smith (LAD) Home Runs
41,0QA239088974#187857841_13L84240Q1475630076Q20,2,239088974,2+,4000,41.000000,41.00,40/1,None Specified,Will Smith (LAD),Unknown,None Specified,410041,['SGP'],"[{'id': '32725', 'name': 'Will Smith (LAD)', '...",Batter Props,Will Smith (LAD) Home Runs
42,0QA239088961#187857842_13L84240Q11617611576Q20,2,239088961,3+,-525,1.190476,1.19,4/21,None Specified,Justin Steele,Unknown,None Specified,11942,['SGP'],"[{'id': '69408', 'name': 'Justin Steele', 'typ...",Pitcher Props,Justin Steele Strikeouts Thrown
43,0QA239088961#187857843_13L84240Q1-1854919473Q20,2,239088961,4+,-210,1.476190,1.47,10/21,None Specified,Justin Steele,Unknown,None Specified,14743,['SGP'],"[{'id': '69408', 'name': 'Justin Steele', 'typ...",Pitcher Props,Justin Steele Strikeouts Thrown
44,0QA239088961#187857844_13L84240Q11484946226Q20,2,239088961,5+,105,2.050000,2.05,21/20,None Specified,Justin Steele,Unknown,True,20544,"['MostBalancedOdds', 'SGP', 'MostBalancedGloba...","[{'id': '69408', 'name': 'Justin Steele', 'typ...",Pitcher Props,Justin Steele Strikeouts Thrown
45,0QA239088961#187857845_13L84240Q11808374608Q20,2,239088961,6+,215,3.150000,3.15,43/20,None Specified,Justin Steele,Unknown,None Specified,31545,['SGP'],"[{'id': '69408', 'name': 'Justin Steele', 'typ...",Pitcher Props,Justin Steele Strikeouts Thrown
46,0QA239088961#187857846_13L84240Q1456030934Q20,2,239088961,7+,425,5.250000,5.25,17/4,None Specified,Justin Steele,Unknown,None Specified,52546,['SGP'],"[{'id': '69408', 'name': 'Justin Steele', 'typ...",Pitcher Props,Justin Steele Strikeouts Thrown
47,0QA239139022#188121774_13L84240Q11617611576Q20,2,239139022,3+,-370,1.270270,1.27,10/37,None Specified,Roki Sasaki,Unknown,None Specified,12774,['SGP'],"[{'id': '494788', 'name': 'Roki Sasaki', 'type...",Pitcher Props,Roki Sasaki Strikeouts Thrown
48,0QA239139022#188121775_13L84240Q1-1854919473Q20,2,239139022,4+,-155,1.645161,1.64,20/31,None Specified,Roki Sasaki,Unknown,None Specified,16475,"['SGP', 'MostBalancedGlobalProbability']","[{'id': '494788', 'name': 'Roki Sasaki', 'type...",Pitcher Props,Roki Sasaki Strikeouts Thrown
49,0QA239139022#188121776_13L84240Q11484946226Q20,2,239139022,5+,135,2.350000,2.35,27/20,None Specified,Roki Sasaki,Unknown,True,23576,"['MostBalancedOdds', 'SGP']","[{'id': '494788', 'name': 'Roki Sasaki', 'type...",Pitcher Props,Roki Sasaki Strikeouts Thrown
50,0QA239139022#188121777_13L84240Q11808374608Q20,2,239139022,6+,290,3.900000,3.90,29/10,None Specified,Roki Sasaki,Unknown,None Specified,39077,['SGP'],"[{'id': '494788', 'name': 'Roki Sasaki', 'type...",Pitcher Props,Roki Sasaki Strikeouts Thrown
51,0QA239139022#188121778_13L84240Q1456030934Q20,2,239139022,7+,600,7.000000,7.00,6/1,None Specified,Roki Sasaki,Unknown,None Specified,70078,['SGP'],"[{'id': '494788', 'name': 'Roki Sasaki', 'type...",Pitcher Props,Roki Sasaki Strikeouts Thrown

In [19]:
def get_stat_tracked(player_line):
    return player_line[PROP_LABEL_STRING].replace(player_line[PARTICIPANT_LABEL_STRING], '').strip().lower()

# choose the value closest to a 50/50 split
# TODO: unders
def decide_to_skip(new_val, old_val):
    new_val_odds = 1 / float(new_val["oddsDecimal"])
    old_val_odds = 1 / float(old_val[new_val['stat_tracked'] + '_' + "Over"])

    new_val_diff = abs(new_val_odds - 0.5)
    old_val_diff = abs(old_val_odds - 0.5)

    return new_val_diff > old_val_diff

In [20]:
final_dk_db = {} #dic so we can combine lines for each player

for index, row in player_lines.iterrows():
    row['stat_tracked'] = get_stat_tracked(row)
    if row[PARTICIPANT_LABEL_STRING] not in final_dk_db:
        final_dk_db[row[PARTICIPANT_LABEL_STRING]] = {
            'name': row[PARTICIPANT_LABEL_STRING]
        }
    elif row['stat_tracked'] in final_dk_db[row[PARTICIPANT_LABEL_STRING]]:
        if (decide_to_skip(row, final_dk_db[row[PARTICIPANT_LABEL_STRING]])):
            continue


    over_or_under = "Over" if "+" in row['label'] else "Under"
    value = float(row['label'].replace("+", '').replace("-", ''))
    print(over_or_under, value)
    final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked']] = value - 0.5 if over_or_under == "Over" else value + 0.5
    final_dk_db[row[PARTICIPANT_LABEL_STRING]][row['stat_tracked'] + '_' + over_or_under] = row['oddsDecimal']


final_dk_db = pd.DataFrame(final_dk_db).T
final_dk_db

Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 1.0
Over 3.0
Over 4.0
Over 5.0
Over 3.0
Over 4.0
Over 5.0

,name,home runs,home runs_Over,strikeouts thrown,strikeouts thrown_Over
Andy Pages,Andy Pages,0.5,6.5,NaN,NaN
Carson Kelly,Carson Kelly,0.5,10.0,NaN,NaN
Dansby Swanson,Dansby Swanson,0.5,7.5,NaN,NaN
Freddie Freeman,Freddie Freeman,0.5,6.5,NaN,NaN
Ian Happ,Ian Happ,0.5,6.5,NaN,NaN
Jon Berti,Jon Berti,0.5,19.0,NaN,NaN
Kyle Tucker,Kyle Tucker,0.5,5.5,NaN,NaN
Matt Shaw,Matt Shaw,0.5,9.5,NaN,NaN
Max Muncy,Max Muncy,0.5,4.8,NaN,NaN
Michael Busch,Michael Busch,0.5,6.5,NaN,NaN
Michael Conforto,Michael Conforto,0.5,7.0,NaN,NaN
Miguel Rojas,Miguel Rojas,0.5,12.0,NaN,NaN
Pete Crow-Armstrong,Pete Crow-Armstrong,0.5,9.5,NaN,NaN
Seiya Suzuki,Seiya Suzuki,0.5,6.0,NaN,NaN
Shohei Ohtani,Shohei Ohtani,0.5,3.8,NaN,NaN
Teoscar Hernandez,Teoscar Hernandez,0.5,4.8,NaN,NaN
Tommy Edman,Tommy Edman,0.5,7.0,NaN,NaN
Will Smith (LAD),Will Smith (LAD),0.5,5.25,NaN,NaN
Justin Steele,Justin Steele,NaN,NaN,4.5,2.05
Roki Sasaki,Roki Sasaki,NaN,NaN,4.5,2.35

In [21]:
final_dk_db

,name,home runs,home runs_Over,strikeouts thrown,strikeouts thrown_Over
Andy Pages,Andy Pages,0.5,6.5,NaN,NaN
Carson Kelly,Carson Kelly,0.5,10.0,NaN,NaN
Dansby Swanson,Dansby Swanson,0.5,7.5,NaN,NaN
Freddie Freeman,Freddie Freeman,0.5,6.5,NaN,NaN
Ian Happ,Ian Happ,0.5,6.5,NaN,NaN
Jon Berti,Jon Berti,0.5,19.0,NaN,NaN
Kyle Tucker,Kyle Tucker,0.5,5.5,NaN,NaN
Matt Shaw,Matt Shaw,0.5,9.5,NaN,NaN
Max Muncy,Max Muncy,0.5,4.8,NaN,NaN
Michael Busch,Michael Busch,0.5,6.5,NaN,NaN
Michael Conforto,Michael Conforto,0.5,7.0,NaN,NaN
Miguel Rojas,Miguel Rojas,0.5,12.0,NaN,NaN
Pete Crow-Armstrong,Pete Crow-Armstrong,0.5,9.5,NaN,NaN
Seiya Suzuki,Seiya Suzuki,0.5,6.0,NaN,NaN
Shohei Ohtani,Shohei Ohtani,0.5,3.8,NaN,NaN
Teoscar Hernandez,Teoscar Hernandez,0.5,4.8,NaN,NaN
Tommy Edman,Tommy Edman,0.5,7.0,NaN,NaN
Will Smith (LAD),Will Smith (LAD),0.5,5.25,NaN,NaN
Justin Steele,Justin Steele,NaN,NaN,4.5,2.05
Roki Sasaki,Roki Sasaki,NaN,NaN,4.5,2.35

In [22]:
prizepicks = pd.read_csv("pp_lines.csv")

merged = pd.merge(prizepicks, final_dk_db, on='name')
#get a list of all the column names
cols = merged.columns.tolist()
merged

,name,opponent,Hits+Runs+RBIs,Hitter Fantasy Score,Walks,Total Bases,Pitcher Strikeouts,Earned Runs Allowed,Pitching Outs,Runs,home runs,home runs_Over,strikeouts thrown,strikeouts thrown_Over
0,Seiya Suzuki,LAD,1.5,5.5,NaN,NaN,NaN,NaN,NaN,NaN,0.5,6.0,NaN,NaN
1,Kyle Tucker,LAD,1.5,5.5,0.5,NaN,NaN,NaN,NaN,NaN,0.5,5.5,NaN,NaN
2,Shohei Ohtani,CHC,NaN,8.5,NaN,1.5,NaN,NaN,NaN,NaN,0.5,3.8,NaN,NaN
3,Teoscar Hernandez,CHC,NaN,6.5,NaN,NaN,NaN,NaN,NaN,NaN,0.5,4.8,NaN,NaN
4,Ian Happ,LAD,NaN,5.5,NaN,NaN,NaN,NaN,NaN,NaN,0.5,6.5,NaN,NaN
5,Roki Sasaki,CHC,NaN,NaN,NaN,NaN,4.0,1.5,NaN,NaN,NaN,NaN,4.5,2.35
6,Justin Steele,LAD,NaN,NaN,NaN,NaN,4.0,NaN,13.5,NaN,NaN,NaN,4.5,2.05
7,Tommy Edman,CHC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0.5,7.0,NaN,NaN
8,Pete Crow-Armstrong,LAD,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,0.5,9.5,NaN,NaN

In [23]:
results = []

for index, row in merged.iterrows():
    # Access the values of each column in the current row
    name = row['name']

    for pp_stat_type in PP_TO_DK_STATS.keys():
        # failsafe 
        if pp_stat_type not in row:
            continue

        if float(row[pp_stat_type]) <= 0:
            continue

        if PP_TO_DK_STATS[pp_stat_type] not in row:
            continue
    
        if float(row[PP_TO_DK_STATS[pp_stat_type]]) <= 0:
            continue

        # Create a dictionary to store the result
        result_dict = {
            'name': name,
            'stat': pp_stat_type,
            'line': row[pp_stat_type],
            'dk_line': float(row[PP_TO_DK_STATS[pp_stat_type]]),
            'dk_over_line': row[PP_TO_DK_STATS[pp_stat_type] + '_Over'],
            'dk_under_line': row[PP_TO_DK_STATS[pp_stat_type] + '_Under'] if PP_TO_DK_STATS[pp_stat_type] + '_Under' in row else 100,
        }

        # Get the dk stat type that corresponds to the current PP stat type
        dk_stat_type = PP_TO_DK_STATS[pp_stat_type]

        # Get the value of the FBref stat type for the current player
        dk_stat_value = row[dk_stat_type]



        # Append the dictionary to the results list
        results.append(result_dict)

results_df = pd.DataFrame(results)
print(results_df.head())


results_df = results_df.dropna()
# results_df = results_df.dropna() 
# # get data types for each column 
# print(results_df.dtypes)

KeyError: 'Total Bases_Over'

In [ ]:
from scipy.stats import poisson
from scipy.optimize import minimize

def implied_odds_at_point(draft_kings_line, lambda_):
        # DraftKings line is an integer threshold (either x.5 or x.0, where x.0 has a push opportunity, so be wary)
        # use the pdf function to get the exact probability of the line
        exact_odds = poisson.pmf(draft_kings_line, lambda_)
        return ((1 - poisson.cdf(draft_kings_line, lambda_)) / (1-exact_odds))


def get_implied_odds(pp_line, draft_kings_line, draft_kings_over_line):
    # Function to solve for lambda
    def solve_lambda(lambda_):
        return abs(implied_odds_at_point(draft_kings_line, lambda_) - (1/draft_kings_over_line))

    # Optimize to find lambda
    # essentially, were setting the two sides of the minus sign to be equal
    result = minimize(solve_lambda, x0=[draft_kings_line], bounds=[(0, None)]) 
    lambda_ = result.x[0]
    print(lambda_, pp_line, draft_kings_line, draft_kings_over_line)
    
    # Calculate the probability of exceeding the pp_line
    prob_over_pp_line = (1 - poisson.cdf(pp_line, lambda_)) / (1 - poisson.pmf(pp_line, lambda_))
    return prob_over_pp_line

results_df["implied_odds"] = results_df.apply(lambda row: get_implied_odds(row["line"], row["dk_line"], row["dk_over_line"]), axis=1)

4.279164804037599 4.0 4.5 2.35
4.605541870557122 4.0 4.5 2.05

In [ ]:
results_df.sort_values(by="implied_odds", ascending=False)

,name,stat,line,dk_line,dk_over_line,dk_under_line,implied_odds
6,Justin Steele,Pitcher Strikeouts,4.0,4.5,2.05,100,0.600295
5,Roki Sasaki,Pitcher Strikeouts,4.0,4.5,2.35,100,0.527665

In [ ]:
results_df = results_df[results_df['line'] == results_df['dk_line']]
results_df.sort_values(by='dk_over_line', ascending=True)

Empty DataFrame
Columns: [name, stat, line, dk_line, dk_over_line, dk_under_line, implied_odds]
Index: []

In [ ]:
results_df.sort_values(by='dk_over_line', ascending=False)

Empty DataFrame
Columns: [name, stat, line, dk_line, dk_over_line, dk_under_line, implied_odds]
Index: []

In [ ]:
import math 
math.sqrt(3)

1.7320508075688772

In [ ]:
1 / math.sqrt(3)

0.5773502691896258

In [ ]:
1 - (0.487 - (115 / 210 - 0.5))

0.5606190476190477